import 'package:flame_audio/flame_audio.dart';

/// Sound effects the game can play.
///
/// Every asset is a short, procedurally synthesised WAV generated by
/// `tool/generate_audio.py` - no third-party or licensed audio is used.
enum SoundEffect {
  button('button.wav'),
  drop('drop.wav'),
  merge('merge.wav'),
  bigMerge('big_merge.wav'),
  combo('combo.wav'),
  booster('booster.wav'),
  levelComplete('level_complete.wav'),
  levelFailed('level_failed.wav'),
  reward('reward.wav');

  const SoundEffect(this.fileName);

  final String fileName;
}

/// Background music tracks.
enum MusicTrack { menu('music_menu.wav'), game('music_game.wav') }

/// Audio playback.
abstract interface class AudioService {
  Future<void> initialize();

  /// Plays [effect] when sound is enabled.
  Future<void> play(SoundEffect effect);

  /// Starts (or restarts) [track] when music is enabled.
  Future<void> playMusic(MusicTrack track);

  Future<void> stopMusic();

  /// Called when the player flips the sound setting.
  void setSoundEnabled(bool enabled);

  /// Called when the player flips the music setting.
  void setMusicEnabled(bool enabled);

  Future<void> dispose();
}

/// Flame Audio backed implementation.
///
/// Sounds are pooled by Flame so repeated merges never allocate a new player,
/// which keeps the merge cascade free of frame hitches.
class FlameAudioService implements AudioService {
  FlameAudioService({this.soundEnabled = true, this.musicEnabled = true});

  bool soundEnabled;
  bool musicEnabled;
  bool _initialised = false;
  MusicTrack? _currentTrack;

  static const String _soundPrefix = 'sounds/';
  static const String _musicPrefix = 'music/';

  @override
  Future<void> initialize() async {
    if (_initialised) return;
    // Flame lazily loads each file the first time it is played, so there is
    // nothing to preload here beyond the music loop.
    _initialised = true;
  }

  @override
  Future<void> play(SoundEffect effect) async {
    if (!soundEnabled || !_initialised) return;
    try {
      await FlameAudio.play(_soundPrefix + effect.fileName);
    } on Object {
      // A missing or unreadable sound must never interrupt gameplay.
    }
  }

  @override
  Future<void> playMusic(MusicTrack track) async {
    if (!musicEnabled || !_initialised) return;
    if (_currentTrack == track) return;
    _currentTrack = track;
    try {
      await FlameAudio.bgm.stop();
      await FlameAudio.loopLongAudio(_musicPrefix + _trackFile(track),
          volume: 0.35);
    } on Object {
      // Music is optional; failures are silent.
    }
  }

  static String _trackFile(MusicTrack track) => switch (track) {
        MusicTrack.menu => 'music_menu.wav',
        MusicTrack.game => 'music_game.wav',
      };

  @override
  Future<void> stopMusic() async {
    _currentTrack = null;
    try {
      await FlameAudio.bgm.stop();
    } on Object {
      // Ignored: stopping music can never fail the game.
    }
  }

  @override
  void setSoundEnabled(bool enabled) => soundEnabled = enabled;

  @override
  void setMusicEnabled(bool enabled) {
    musicEnabled = enabled;
    if (!enabled) {
      // Fire and forget: the caller does not need to await a settings toggle.
      stopMusic();
    }
  }

  @override
  Future<void> dispose() async {
    await stopMusic();
    _initialised = false;
  }
}

/// No-op implementation used by tests and by builds without audio assets.
class NoopAudioService implements AudioService {
  const NoopAudioService();

  @override
  Future<void> initialize() async {}

  @override
  Future<void> play(SoundEffect effect) async {}

  @override
  Future<void> playMusic(MusicTrack track) async {}

  @override
  Future<void> stopMusic() async {}

  @override
  void setSoundEnabled(bool enabled) {}

  @override
  void setMusicEnabled(bool enabled) {}

  @override
  Future<void> dispose() async {}
}
